### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by FaynaStalwart** [Siterizer/new-world-fishing-bot#113]
I was changing some of the config stuff because it kept trying to start the fishing catch before it was ready, than this started to pop up and now won't stop popping up. can help please? also about what I need to change for it trying to catch it too early?

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "gui\gui_functions.py", line 57, in start_fishing
  File "functionality\fishing_loop.py", line 26, in fishing_loop
  File "utils\config.py", line 193, in random_timeout
  File "random.py", line 513, in uniform
TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by FaynaStalwart** [comment]
I'm not completely sure what I should be doing. does the python version work better?
