### ISSUE TITLE
always crashing after 10 minutes

### ISSUE THREAD

**Issue by dvz95** [Siterizer/new-world-fishing-bot#168]
see above

**Comment by dvz95** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "tkinter\__init__.py", line 814, in callit
  File "functionality\fishing_loop.py", line 13, in fishing_loop
  File "functionality\fishing_loop.py", line 31, in call_appropriate_fishing_action
  File "functionality\image_recognition.py", line 16, in image_recognition_result
  File "PIL\ImageGrab.py", line 43, in grab
OSError: screen grab failed

**Comment by Siterizer** [comment]
@dvz95 I think it's about dual monitor setup. after 10minutes can mean the 'repairing' time, can you pls turn repair off and let me know if that helped?

**Comment by andreijoda** [comment]
in case I have two monitors and that happens.  got any solution?

Sorry my bad English.
