### ISSUE TITLE
Error when trying to repair

### ISSUE THREAD

**Issue by chasechou** [Siterizer/new-world-fishing-bot#230]
For the most part, this is working wonderfully except when it tries to do a repair then I am running into this issue below. I did modify the script to use my keybind which you'll see here where it's trying to press '=' which is my fishing key. Any ideas?

> [INFO] Green color spotted, Reeling a fish
[INFO] Cast fishing rod
[INFO] Waiting for fish...
[INFO] Repairing
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\Chase\Desktop\streamdeck\functionality\fishing_loop.py", line 21, in fishing_loop
    repairing()
  File "C:\Users\Chase\Desktop\streamdeck\functionality\fishing_actions.py", line 46, in repairing
    arm_disarm_fishing_rod(arm_disarm_timeout)
  File "C:\Users\Chase\Desktop\streamdeck\functionality\fishing_actions.py", line 72, in arm_disarm_fishing_rod
    press_key('=')
  File "C:\Users\Chase\Desktop\streamdeck\wrappers\win32api_wrapper.py", line 21, in press_key
    win32api.keybd_event(VK_CODE[key], 0,0,0)
KeyError: '='

**Comment by Siterizer** [comment]
@chasechou Well you should add this line:
`"=": 0xBB,`
here:
https://github.com/Siterizer/new-world-fishing-bot/blob/297aeb4ef15ee8dd2673530d262fc361b06b676e/wrappers/win32api_wrapper.py#L13

**Comment by chasechou** [comment]
This worked, thanks!
