### ISSUE TITLE
cv2.error

### ISSUE THREAD

**Issue by Krampus12** [Siterizer/new-world-fishing-bot#65]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "gui\gui_functions.py", line 47, in start_fishing
  File "functionality\fishing_loop.py", line 13, in fishing_loop
  File "functionality\fishing_loop.py", line 28, in call_appropriate_fishing_action
  File "functionality\image_recognition.py", line 17, in image_recognition_result
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

I'm getting this error, can anyone help me?

**Comment by Siterizer** [comment]
https://github.com/Siterizer/new-world-fishing-bot/issues/17
Sorry but i don't know how to help you :(
