### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by mherasevich** [Siterizer/new-world-fishing-bot#72]
I faced with the error while tried to run the bot:

```
PS D:\aaa\new-world-fishing-bot> python bot.py
Traceback (most recent call last):
  File "D:\aaa\new-world-fishing-bot\bot.py", line 2, in <module>
    from gui.gui_initializer import gui_init
  File "D:\aaa\new-world-fishing-bot\gui\gui_initializer.py", line 2, in <module>
    from gui.gui_functions import start_fishing, on_closing
  File "D:\aaa\new-world-fishing-bot\gui\gui_functions.py", line 4, in <module>
    from functionality.fishing_loop import fishing_loop
  File "D:\aaa\new-world-fishing-bot\functionality\fishing_loop.py", line 3, in <module>
    from functionality.image_recognition import image_recognition_result
  File "D:\aaa\new-world-fishing-bot\functionality\image_recognition.py", line 3, in <module>
    import cv2 as cv
  File "C:\Users\dev\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: The specified module could not be found.
```

package list:
```
PS D:\aaa\new-world-fishing-bot> pip list
Package               Version
--------------------- -----------
numpy                            1.21.2
opencv-contrib-python  4.5.3+dummy
opencv-python               4.5.3.56
Pillow                              8.3.2
pip                                  21.2.4
pypiwin32                       223
pywin32                          301
PyYAML                           5.4.1
```

Python version:
```
PS D:\aaa\new-world-fishing-bot> python --version
Python 3.9.7
```

Please help me to solve this issue 🙏

**Comment by Landmine-1252** [comment]
Check your openvc version

Mine is working with the following, I did a few more packages because I was browsing the code in vscode:

```
(venv) PS E:\temp\new-world-fishing-bot> pip list
Package           Version
----------------- --------
astroid           2.8.2
colorama          0.4.4
flake8            3.9.2
isort             5.9.3
lazy-object-proxy 1.6.0
mccabe            0.6.1
numpy             1.21.2
opencv-python     4.5.3.56
Pillow            8.3.2
pip               21.2.3
platformdirs      2.4.0
pycodestyle       2.7.0
pyflakes          2.3.1
pylint            2.11.1
pywin32           301
PyYAML            5.4.1
setuptools        57.4.0
toml              0.10.2
typing-extensions 3.10.0.2
wrapt             1.12.1

(venv) PS E:\temp\new-world-fishing-bot> python --version
Python 3.9.7

```

**Comment by Siterizer** [comment]
Try to uninstall python and install again, maybe this would help :)

**Comment by zak062** [comment]
I ran into this issue along with a few others while trying to install. I finally got it to work with these steps (idk which one actually "fixed" it) I had tried all the below steps at other times but this order of steps are what worked for me

Uninstalled Python
Downgrade to 3.8.10 (https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip)
Installed each package listed in requirements.txt with pip
Download zip of bot, extract to directory
created the virtual env
activated scripts
ran pip -install installpath\requirements.txt
cd installdirectory
py bot.py

**Comment by zak062** [comment]
@Siterizer 
I think you're right, I did also get it to work with 3.9.7 following my same steps, even though that was the package that was originally installed for me. Now I just can't get the bot to reel the fish in. 
@yfchina143 
try running pip install --upgrade pip while in the venv to see if that resolved your issue. If it doesn't, whats the command you're running?
