### ISSUE TITLE
Exception in Tkinter (not running)

### ISSUE THREAD

**Issue by Acanis87** [Siterizer/new-world-fishing-bot#95]
Hey, I just downloaded the ZIP, did everything in the manual and I get this error message:

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "tkinter\__init__.py", line 1892, in __call__
>  File "gui\gui_functions.py", line 57, in start_fishing
> File "functionality\fishing_loop.py", line 13, in fishing_loop
> File "functionality\fishing_loop.py", line 31, in call_appropriate_fishing_action
> File "functionality\image_recognition.py", line 18, in image_recognition_result
> cv2.error: OpenCV(4.5.3) 
> C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\templmatch.cpp:1164: 
> error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) 
> && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

The bot is not doing anything ingame. Anyone an idea?! :)

**Comment by Acanis87** [comment]
Oh, couldnt find that with the search... Thank you^^ If using Python and the script does help, Ill try that :) 

Iam using Windows 10 (newest update).
